controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
api_login_check:
    path: /api/login_check

user_register:
    path: /register
    controller: App\Controller\UserController::register
    methods: ['POST']

user_login:
    path: /login
    controller: App\Controller\UserController::login
    methods: ['POST']

user_logout:
    path: /logout
    controller: App\Controller\UserController::logout
    methods: ['POST']
